### ISSUE TITLE
Base table or view not found: 1146 Table 'admin_test.permissions' doesn't exist

### ISSUE THREAD

**Issue by sachinvrg** [chacbumbum/learn_laravel#1]
I am getting this error when run following command -

php artisan clear-compiled
Error -
` [Illuminate\Database\QueryException]                                                                                                 
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_test.permissions' doesn't exist (SQL: select * from `permissions`)                                                                                                  
  [PDOException]                                                                                    
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_test.permissions' doesn't exist  
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 1
`

**Comment by chacbumbum** [comment]
I'm so sorry. This is a project when I first started learning about angular.

I have to fix it 3b48843

That day I wrote code very dirty :D

You can install and run it, but do not read it :-1: 

Thank you :)

**Comment by sachinvrg** [comment]
I am wondering man !!! Why do you use 'Angular' tag ??? Where did you use Angular js? Please either explain or remove this tag so that other users won't be misguided.

**Comment by chacbumbum** [comment]
As you can see. There is an angular branch but I do not leave it in default.
